# Site settings
title:       Chris Wahlfeldt
email:       chriswahlfeldt@gmail.com
author:      Chris Wahlfeldt
description: "This is my personal site and I use it to post my projects and write about things that include: stuff im working on, videogames, 3D stuff, the 'interweb', and how to make shit!"
baseurl:     ""
url:         "/"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: waffleiron

# Social icons
show_social_icons: true # in header
github_username: cwahlfeldt
stackoverflow_id: 3534217
twitter_username:
google_plus_id:
linkedin_username: chriswahlfeldt@gmail.com
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus:
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
